database:
    adapter: mysql
    host: localhost
    username: myuser
    password: mypass
    database: somedatabase

number_mod_cols: 8

synonyms:
    # Note that underscored versions of multiple words will also be included.
    # The 50 states + abbreviations
    - [AL, Alabama]
    - [AK, Alaska]
    - [AS, American Samoa]
    - [AZ, Arizona]
    - [AR, Arkansas]
    - [CA, California]
    - [CO, Colorado]
    - [CT, Connecticut]
    - [DE, Delaware]
    - [DC, District Of Columbia]
    - [FM, Federated States Of Micronesia]
    - [FL, Florida]
    - [GA, Georgia]
    - [GU, Guam]
    - [HI, Hawaii]
    - [ID, Idaho]
    - [IL, Illinois]
    - [IN, Indiana]
    - [IA, Iowa]
    - [KS, Kansas]
    - [KY, Kentucky]
    - [LA, Louisiana]
    - [ME, Maine]
    - [MH, Marshall Islands]
    - [MD, Maryland]
    - [MA, Massachusetts]
    - [MI, Michigan]
    - [MN, Minnesota]
    - [MS, Mississippi]
    - [MO, Missouri]
    - [MT, Montana]
    - [NE, Nebraska]
    - [NV, Nevada]
    - [NH, New Hampshire]
    - [NJ, New Jersey]
    - [NM, New Mexico]
    - [NY, New York]
    - [NC, North Carolina]
    - [ND, North Dakota]
    - [MP, Northern Mariana Islands]
    - [OH, Ohio]
    - [OK, Oklahoma]
    - [OR, Oregon]
    - [PW, Palau]
    - [PA, Pennsylvania]
    - [PR, Puerto Rico]
    - [RI, Rhode Island]
    - [SC, South Carolina]
    - [SD, South Dakota]
    - [TN, Tennessee]
    - [TX, Texas]
    - [UT, Utah]
    - [VT, Vermont]
    - [VI, Virgin Islands]
    - [VA, Virginia]
    - [WA, Washington]
    - [WV, West Virginia]
    - [WI, Wisconsin]
    - [WY, Wyoming]
    # The common abbreviations for animal names or sources
    - [CK, Chicken]
    - [DK, Duck]
    - [MD, Mallard, Mallard duck]
    - [GS, Goose]
    - [SW, Swine]
    - [EM, Environment]
    - [AB, Aquatic bird]
    # Other countries and places that pop up a lot
    - [VN, Vietnam, Viet Nam]
    - [HK, Hong Kong]
    - [NC, New Caledonia]
    - [PR, Puerto Rico]
    - [GD, Guangdong, Guang Dong]
    - [BM, Brevig Mission]
    - [WSN, "Wilson-Smith"]
    - [MX, Mexico]
    - [SI, Solomon Island, Solomon Islands]
    - [NL, Netherlands]